export const GET_DISCUSSIONS = "GET_DISCUSSIONS";
export const REGISTER_SUBMIT = "REGISTER_SUBMIT";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
